export const rackMaterialTypes = [
    "1-space Blank",
    "2-space Blank",
    "3-space Blank",
    "1-space vent",
    "2-space vent",
    "3-space vent",
    "Rack Screw",
    "Lacing Strip",
    "Wire Tie",
    'Flexo 1/2"-1 1/4"',
    'Flexo 1 1/4" - 2 3/4"',
    'PET (velcro) 1 1/2"',
    'PET (velcro) 2"',
    '12" power cord',
    '18" Power Cord',
    '24" Power Cord',
    "Premade",
  ];